package JMSCAPI.misc;

public interface CryptDuplicateHash_misc {
	/**
	 * The error codes prefaced by NTE are generated by the particular CSP being used.
	 * Some possible error codes returned by <b>GetLastError()</b>:
	 *																										</p><table><tr>
	 *<td>ERROR_CALL_NOT_IMPLEMENTED</td>	<td>Because this is a new function, existing CSPs cannot
	 *											implement it. This error is returned if the CSP does
	 *											not support this function.									</td></tr><tr>
	 *
	 *<td>E_NOTIMPL=80004001h</td>			<td>Same as previous.											</td></tr><tr>
	 *
	 *<td>ERROR_INVALID_PARAMETER = 87</td>	<td>One of the parameters contains a value that is not
	 * 										valid. This is most often a pointer that is not valid.			</td></tr><tr>
	 * 
	 *<td>NTE_BAD_HASH</td>					<td>The hash object specified by the <code>hHash</code>
	 *											parameter is not valid.										</td></tr>
	 *																										</table>

	*/
		public static String error_codes = "error codes";
}
