package JMSCAPI.misc;

public interface CryptDestroyKey_misc {
/**
 * The error codes prefaced by NTE are generated by the particular CSP being used.
 * Some possible error codes returned by <b>GetLastError()</b>:
 *																										</p><table><tr>
 *<td>ERROR_BUSY</td>					<td>The key object specified by <b>hKey</b> is currently
 *											being used and cannot be destroyed.							</td></tr><tr>
 *
 *<td>ERROR_INVALID_HANDLE</td>			<td>The <b>hKey</b> parameter specifies a handle that is
 *											not	valid.													</td></tr><tr>
 *
 *<td>ERROR_INVALID_PARAMETER = 87</td>	<td>The <b>hKey</b> parameter specifies a value that is
 *											not	valid.													</td></tr><tr>
 * 
 *<td>NTE_BAD_KEY</td>					<td>The <b>hKey</b> parameter does not contain a valid
 *											handle to a key.											</td></tr><tr>
 *
 *<td>NTE_BAD_UID</td>					<td>The CSP context that was specified when the key was
 *											created cannot be found.									</td></tr>
 *																										</table>

*/
	public static String error_codes = "error codes";
}
