package JMSCAPI.misc;

/**

	 
 * 
 *
 */
public interface CryptEnumProviders_misc {
	/**
	 * The error codes prefaced by NTE are generated by the particular CSP being used.
	 * Some possible error codes returned by <b>GetLastError()</b>:
	 *																									</p><table><tr>
	 * <td>ERROR_MORE_DATA</td>			<td>The <b>pszProvName</b> buffer was not large enough 
	 * 										to hold the provider name.									</td></tr><tr>
	 * <td>ERROR_NO_MORE_ITEMS</td>		<td>There are no more items to enumerate.						</td></tr><tr>
	 * <td>ERROR_NOT_ENOUGH_MEMORY</td>	<td>The operating system ran out of memory.						</td></tr><tr>
	 * <td>NTE_BAD_FLAGS</td>			<td>The <b>dwFlags</b> parameter has an unrecognized value.		</td></tr><tr>
	 * <td>NTE_FAIL	</td>				<td>Something was wrong with the type registration.				</td></tr>
	 *																									</table> 
	 */
	public static String error_codes = "error codes";
	

}
