package JMSCAPI.misc;

public interface CryptHashData_misc {

	/**
	 * All Microsoft Cryptographic Providers ignore this parameter. For any CSP that does not
	 * ignore this parameter, if this flag is set, the CSP prompts the user to input data directly.
	 * This data is added to the hash. The application is not allowed access to the data. This flag
	 * can be used to allow the user to enter a PIN into the system.
	 */
	public static final int CRYPT_USERDATA = 1;
	
	/**
	 * The error codes prefaced by NTE are generated by the particular CSP being used.
	 * Some possible error codes returned by <b>GetLastError()</b>:
	 *																										</p><table><tr>
	 *<td>ERROR_INVALID_HANDLE</td>			<td>One of the parameters specifies a handle that is
	 *											not valid.													</td></tr><tr>
	 *
	 *<td>ERROR_INVALID_PARAMETER = 87</td>	<td>One of the parameters contains a value that is not
	 * 										valid. This is most often a pointer that is not valid.			</td></tr><tr>
	 * 
	 *<td>NTE_BAD_ALGID</td>				<td>The <code>hHash</code> handle specifies an algorithm
	 *											that this CSP does not support.								</td></tr><tr>
	 *
	 *<td>NTE_BAD_FLAGS</td>				<td>The <b>dwFlags</b> parameter has a value that is
	 *											not valid.													</td></tr><tr>
	 *
	 *<td>NTE_BAD_HASH</td>					<td>The hash object specified by the <code>hHash</code>
	 *											parameter is not valid.										</td></tr><tr>
	 *
	 *<td>NTE_BAD_HASH_STATE</td>			<td>An attempt was made to add data to a hash object that
	 *											is already marked "finished."								</td></tr><tr>
	 *
	 *<td>NTE_BAD_KEY</td>					<td>A keyed hash algorithm is being used, but the session
	 *											key is no longer valid. This error is generated if
	 *											the session key is destroyed before the hashing
	 *											operation is complete.										</td></tr><tr>
	 *
	 *<td>NTE_BAD_LEN</td>					<td>The CSP does not ignore the <code>CRYPT_USERDATA</code>
	 *											flag, the flag is set, and the <code>dwDataLen</code>
	 *											parameter has a nonzero value.								</td></tr><tr>
	 * 
	 *<td>NTE_FAIL</td>						<td>The function failed in some unexpected way.					</td></tr><tr>
	 *
	 *<td>NTE_NO_MEMORY</td>				<td>The CSP ran out of memory during the operation.				</td></tr><tr>
	 *
	 *<td>NTE_BAD_UID</td>					<td>The CSP context that was specified when the hash was
	 *											created cannot be found.									</td></tr>
	 *																										</table>
	 */
	public static String error_codes = "error codes";
}
