package JMSCAPI.misc;

public interface CryptImportKey_misc {
	
	/**
	 * Possible dwFlags:<ul>
	 * <li>{@link KeyFlags#CRYPT_EXPORTABLE CRYPT_EXPORTABLE}</li>
	 * <li>{@link KeyFlags#CRYPT_OAEP CRYPT_OAEP}</li>
	 * <li>{@link KeyFlags#CRYPT_NO_SALT CRYPT_NO_SALT}</li>
	 * <li>{@link KeyFlags#CRYPT_USER_PROTECTED CRYPT_USER_PROTECTED}</li>
	 * <li>{@link KeyFlags#CRYPT_IPSEC_HMAC_KEY CRYPT_IPSEC_HMAC_KEY}</li>
	 * </ul>
	 */
	public static String dwFlags = "dwFlags";
	
	
	/**
	 * 	
	 * The error codes prefaced by NTE are generated by the particular CSP being used.
	 * Some possible error codes returned by <b>GetLastError()</b>:
	 *																										</p><table><tr>
	 *<td>ERROR_INVALID_HANDLE</td>			<td>One of the parameters specifies a handle that is
	 *											not valid.													</td></tr><tr>
	 *
	 *<td>ERROR_INVALID_PARAMETER = 87</td>	<td>One of the parameters contains a value that is not
	 * 										valid. This is most often a pointer that is not valid.			</td></tr><tr>
	 * 
	 *<td>ERROR_BUSY</td>					<td>Some CSPs set this error if a private key is imported
	 *											into a container while another thread or process is
	 *											using this key.												</td></tr><tr>
	 *
	 *<td>NTE_BAD_DATA</td>					<td>Either the algorithm that works with the public key to
	 *											be imported is not supported by this CSP, or an attempt
	 *											was made to import a session key that was encrypted with
	 *											something other than one of your public keys.				</td></tr><tr>
	 *
	 *<td>NTE_BAD_FLAGS</td>				<td>The dwFlags parameter specified is not valid.				</td></tr><tr>

	 *<td>NTE_BAD_ALGID</td>				<td>The simple key BLOB to be imported is not encrypted with
	 *											the expected key exchange algorithm.						</td></tr><tr>

	 *<td>NTE_BAD_TYPE</td>					<td>The key BLOB type is not supported by this CSP and is
	 *											possibly not valid.											</td></tr><tr>
	 *
	 *<td>NTE_BAD_UID</td>					<td>The hProv parameter does not contain a valid context handle.</td></tr><tr>
	 *
	 *<td>NTE_BAD_VER</td>					<td>The version number of the key BLOB does not match the CSP
	 *											version. This usually indicates that the CSP needs
	 *											to be upgraded.												</td></tr>
	 *																										</table>
		 */
	public static String error_codes = "error codes";
	

}
