package JMSCAPI.misc;

public interface CryptGetUserKey_misc {
/**
 * The error codes prefaced by NTE are generated by the particular CSP being used.
 * Some possible error codes returned by <b>GetLastError()</b>:
 *																										</p><table><tr>
 *<td>ERROR_INVALID_HANDLE</td>			<td>One of the parameters specifies a handle that is
 *											not valid.													</td></tr><tr>
 *
 *<td>ERROR_INVALID_PARAMETER = 87</td>	<td>One of the parameters contains a value that is not
 * 										valid. This is most often a pointer that is not valid.			</td></tr><tr>
 * 
 *<td>NTE_BAD_KEY</td>					<td>The <b>dwKeySpec</b> parameter contains a value that
 *											is not valid.												</td></tr><tr>
 *
 *<td>NTE_BAD_UID</td>					<td>The <b>hProv</b> parameter does not contain a valid
 *											context handle.												</td></tr><tr>
 *
 *<td>NTE_NO_KEY</td>					<td>The key requested by the dwKeySpec parameter does 
 *											not exist.													</td></tr>
 *																										</table>

	 */
	public static String error_codes = "error codes";
/* <td></td><td></td></tr><tr>*/
}
